### ISSUE TITLE
Improve Audit Trail Output

### ISSUE THREAD

**Issue by samkeen** [samkeen/kiln#28]
Current Output:

```yaml
executionUuid: 55db867c03e74d5e0
startTime: '1440450172.0158'
amiBuildQueueUrl: >
  https://sqs.us-west-2.amazonaws.com/182026393062/kiln-KilnBuildRequestQueue-J3BNUEQTBXUB
jobMessage:
  Body: |
    {
      "templatename": "testing/just-prove-it-works.json",
      "sha": "647d8d320bd0459f49b87cdfc5f6aa8c2c481a5b"
    }
  MD5OfBody: f6a16154a4cc03d4ee176851ae21ca84
  MessageId: 2edc6082-fc93-45d9-a958-8b4287caf753
jobBuildTemplate: testing/just-prove-it-works.json
jobBuildTemplateSha: 647d8d320bd0459f49b87cdfc5f6aa8c2c481a5b
jobReceived: true
createdAmiId: ami-b7d7c187
createdAmiRegion: us-west-2
endedInError: false
endTime: '1440450386.6658'
```

Add `Time Taken` in min/secs

Add start time formated in human format (iso8601)
